build:
  commands:
    - echo "Building Maven project..."
    - mvn clean package -DskipTests

    - echo "Current directory:"
    - pwd

    - echo "Project files:"
    - ls -la

    - echo "Target directory:"
    - ls -la target || true

    - echo "Building Docker image..."
    - docker build -t $REPOSITORY_NAME .
    - docker tag $REPOSITORY_NAME:latest $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$REPOSITORY_NAME:$IMAGE_TAG
