version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 762794225187.dkr.ecr.us-east-2.amazonaws.com
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-7)

  build:
    commands:
      - echo Building Docker image...
      - docker build -t 762794225187.dkr.ecr.us-east-2.amazonaws.com/secret-santa:latest .
      - docker tag 762794225187.dkr.ecr.us-east-2.amazonaws.com/secret-santa:latest 762794225187.dkr.ecr.us-east-2.amazonaws.com/secret-santa:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing to ECR...
      - docker push 762794225187.dkr.ecr.us-east-2.amazonaws.com/secret-santa:latest
      - docker push 762794225187.dkr.ecr.us-east-2.amazonaws.com/secret-santa:$IMAGE_TAG
      - echo Build complete!
